Fix wrong deadline date in check in copy
hackclub-archive/api pull request #134
Opened 2017-03-13 10:13 UTC by MaxWofford

Closes https://github.com/hackclub/api/issues/133

2017-03-13 20:59 UTC, paked requested changes

2017-03-13 20:59 UTC, paked commented on app/models/leader.rb
> +    Rails.logger.warn("Unable to find timezone for leader \##{id}")
Not sure this log statement is inline with the other precedent in the code base.

2017-03-13 20:59 UTC, paked commented on app/models/hackbot/conversations/check_in.rb
> +        timezone = lead.timezone || Timezone.fetch('America/Los_Angeles')
Where does `lead.timezone` come from?

2017-03-14 04:25 UTC, MaxWofford commented on app/models/hackbot/conversations/check_in.rb
> +        timezone = lead.timezone || Timezone.fetch('America/Los_Angeles')
https://github.com/hackclub/api/pull/134/files/bf5ecdd457f157239f4b24bde8bea3cda80873cf#diff-2320146b278b59957e7aae3cc2fd5f84R65

2017-03-14 04:26 UTC, MaxWofford commented on app/models/leader.rb
> +    Rails.logger.warn("Unable to find timezone for leader \##{id}")
Let's chat on slack or in-person about this.

2017-03-14 04:34 UTC, paked commented on app/models/hackbot/conversations/check_in.rb
> +        timezone = lead.timezone || Timezone.fetch('America/Los_Angeles')
Oh. Wow. Tripping out apparently.

2017-03-16 22:06 UTC, paked commented
@MaxWofford: Can you update this to master?

2017-03-16 22:06 UTC, paked approved these changes

2017-03-16 22:43 UTC, MaxWofford commented
Updated!

2017-03-16 23:14 UTC, merged