Add set club stage command
hackclub-archive/api pull request #240
Opened 2017-05-05 11:00 UTC by MaxWofford

2017-05-05 23:34 UTC, MaxWofford commented
The things to test are:

1. Set active club to dormant, then back to active
1. Set club to active again, and it should warn that it already was in that stage
1. Link your leader to 2 clubs, then set the stage of one of the clubs
1. Link your leader to 2 clubs, then try pressing the club select buttons from a different slack account

2017-05-05 23:38 UTC, MaxWofford commented
Forgot the admin command tests:

1. Normal flow of setting one club with a valid streak_key
1. Try setting a club with an invalid streak_key
1. Try setting a club to an invalid stage
1. Try starting the command from a non-admin account

2017-05-06 00:06 UTC, paked requested changes
A few things:

- We need to record the date in which clubs moving to dormant are going to come back. Otherwise for all we know they're just dead. Check out the `check_in.rb` file for a reasonable guide on how to do this.
- We need to either consistently be using `club.make_{active,dormant}` or just setting the stage directly with a string (`club.stage_key = "XYZ" && club.save`)
- The code here is great. Good job.

2017-05-08 20:55 UTC, paked commented
@MaxWofford: Can you fix the tests?

2017-05-09 07:32 UTC, paked commented on app/models/club.rb
> +    SlackClient::Chat.send_msg(
Should we turn this into a conversation?

2017-05-09 07:35 UTC, paked commented on app/models/hackbot/interactions/set_club.rb
> +      def set_single_club
Want to bring up my concerns here again:

This is a different method of setting the stage key than we used in the `CheckIn` class. In the `CheckIn` class we used the `make_dormant` and `make_active` helper functions which I wrote.

2017-05-09 15:53 UTC, MaxWofford commented on app/models/hackbot/interactions/set_club.rb
> +      def set_single_club
@paked I think they have different functions. The set_club interaction is set up to quickly work with any stage in Streak.

2017-05-11 05:43 UTC, paked commented
@MaxWofford: Blocking on you to make the changes we discussed in-person.

2017-05-12 21:26 UTC, MaxWofford commented
@paked changed!

2017-06-19 19:20 UTC, paked commented
@MaxWofford: What are we doing here?

Worth closing?

2017-06-30 21:01 UTC, MaxWofford commented
Closing this because it's not relevant to our current work. Might reopen later if we decide we need this command.

2017-06-30 21:01 UTC, closed without merging