Add status messages to associate teachers task
hackclub-archive/api pull request #76
Opened 2017-02-23 20:10 UTC by MaxWofford

2017-02-23 20:11 UTC, MaxWofford commented
@zachlatta The goal of this it to get a sense of how far the rake task is to completing.

2017-02-23 20:20 UTC, MaxWofford commented
Reassigning to @paked because team bandwidth.

2017-02-23 23:03 UTC, paked requested changes

2017-02-23 23:03 UTC, paked commented on lib/tasks/outreach/teacher_emails/associate_teachers.rake
> +      puts "Starting index \##{i} out of #{total}"
Shouldn't you put a mutex on stdout?

2017-02-24 00:23 UTC, MaxWofford commented on lib/tasks/outreach/teacher_emails/associate_teachers.rake
> +      puts "Starting index \##{i} out of #{total}"
@paked Just added.

2017-02-26 18:14 UTC, merged

2017-02-26 18:15 UTC, paked commented
![https://media.giphy.com/media/xsgOm2eD9od5C/giphy.gif](https://media.giphy.com/media/xsgOm2eD9od5C/giphy.gif)

WOo